version: '3.3'
services:
  frontend:
    build: frontend/.
    environment: 
      - PORT=${FE_PORT}
    ports:
      - 3000:${FE_PORT}
  backend:
    build: backend/.
    environment:
      - SPRING_PROFILES=local
      - PORT=${BE_PORT}
    ports:
      - 8080:${BE_PORT}
