version: '3.3'
services:
  frontend:
    build: frontend/.
    environment: 
      - NGINX_PORT=${FE_PORT}
    ports:
      - 3000:${FE_PORT}
  backend:
    build: backend/.
    ports:
      - 8080:8080
