spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    root: INFO
pitanga:
  room:
    min-id: 10000000
    max-id: 99999999
  web-socket:
    paths:
      - pitanga
    allowed-origins:
      - http://localhost:3000
