spring:
  jpa:
    show-sql: true
    open-in-view: false
  properties:
    hibernate:
      format_sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    root: INFO
    org.springframework.transaction.interceptor: INFO # TRACE
pitanga:
  room:
    min-id: 10000000
    max-id: 99999999
    max-rooms: 4
    max-users: 4
  web-socket:
    paths:
      - pitanga
    allowed-origins:
      - http://localhost:3000
  user:
    max-users: 4
    icons:
      - ☕
      - 🍗
      - ⭐
      - 🎀
