server:
  port: ${PORT:8080}
spring:
  profiles:
    active: ${SPRING_PROFILES:}
  jpa:
    open-in-view: false
    show-sql: false
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    database-platform: org.hibernate.dialect.H2Dialect
pitanga:
  room:
    min-id: 10000000
    max-id: 99999999
    max-rooms: 16
    max-users: 40
  web-socket:
    paths:
      - pitanga
    allowed-origins:
      - http://pitanga.figtreelake.com
      - https://pitanga.figtreelake.com
      - http://marceloleite2604.github.io
      - https://marceloleite2604.github.io
  user:
    max-users: 4
    icons:
      - ☕
      - 🍗
      - ⭐
      - 🎀