name: Deploy on Heroku

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build front end
        run: make build-frontend
        
      - name: Build back end
        run: make build-backend

      - name: Login to Heroku Container Registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
        
#       - name: Build and push frontend container
#         env: 
#           HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
#         run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web 
