name: Deploy on Heroku

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-back-end:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
          
      - name: Build back end executable
        run: make build-backend

      - name: Build, push and release back end container
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          cd backend
          heroku container:login
          heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
          heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
          
  build-front-end:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Build front end
        run: make build-frontend
        
      - name: Deploy front end on GitHub pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: frontend/build
